### PR TITLE
corrected spelling and article errors!! ❤✔

### PR DESCRIPTION
**Pull request by satyamroy001**
## Where
https://github.com/NimbleEdge/EnvisEdge/blob/main/docs/source/tutorials/Tutorial-Part-4-deployment.rst
## Description
1. corrected spelling of capabilities
2. corrected spelling of dependencies
3. corrected the verb form to serialize
4. corrected spelling of themselves

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by ramesht007** [comment]
Combine PR #249 and #248.
Then we can merge it

**Comment by satyamroy001** [comment]
> Combine PR #249 and #248. Then we can merge it

I can't able to merge the PRs please help sir @ramesht007

**Comment by ramesht007** [comment]
> > Combine PR #249 and #248. Then we can merge it
> 
> I can't able to merge the PRs please help sir @ramesht007

Close both PR and add both changes into one PR.

**Comment by satyamroy001** [comment]
@ramesht007 sir check this I have merged them in single PR

**Review by ramesht007 — APPROVED** [review]

**Review by ramesht007 — CHANGES_REQUESTED** [review]
Please fix the conflicts before we can merge

**Comment by satyamroy001** [comment]
Done @ramesht007 sir

**Review by satyamroy001 — COMMENTED** [review]
Done

**Review by ramesht007 — APPROVED** [review]
LGTM!!

**Pull request merged**
