### PR TITLE
Correcting the grammatical errors in many files

### PR DESCRIPTION
**Pull request by soma2000-lang**
## Description
In the docs folder of envis edge there are several files having grammatical errors.Those have been corrected in this PR.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by ramesht007** [comment]
Why are the files deleted @soma2000-lang ?

**Comment by soma2000-lang** [comment]
@ramesht007 These 2 files are deleted in this pr  because I already had created seperate pr for the inline documentation of these 2 files

**Comment by soma2000-lang** [comment]
@ramesht007 Please see if this pr can be merged

**Comment by ramesht007** [comment]
Please add these changes separately, these files should not be deleted.
and also resolve the merge conflicts.
thanks

**Comment by soma2000-lang** [comment]
@ramesht007  I have resolved the merge conflict. Now how should "add these changes separately," so that the files are not deleted.

**Comment by ramesht007** [comment]
hey @soma2000-lang ,
If you have resolved the merge conflict, then please close this PR.
and put a new one with all files intact.

**Comment by soma2000-lang** [comment]
Ok @ramesht007 .

**Pull request closed without merging**
