### PR TITLE
Created Inline Documentation for  EnvisEdge/fedrec/utilities/io_utils.py 

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
## Description
Added Inline documentation to 8 functions under the io_utis.py files 

## Relevant Issue
Issue #192 the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented on my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

### CODE REVIEW

**Review by ramesht007 — CHANGES_REQUESTED** [review]
please follow these documentation guidelines:
pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

and refactor your comments.
thanks

**Comment by ramesht007** [comment]
any udpates on this @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
Hi @ramesht007, I would be unable to complete this issue due to my exams.
Thank you all for your support but you can unassign me right now.

**Comment by ramesht007** [comment]
ok, no problem.
you can try and complete after exam if this issue is still open.
best of luck
thanks

**Pull request closed without merging**
